# Generated by Django 2.0.2 on 2019-11-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='appearances',
            field=models.IntegerField(),
        ),
    ]
